### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cristianikoh** [Deijin27/RanseiLink#74]
### What happened?

Error appeared when trying to populate graphics default

### Version

6.0

### Error Message

Application.Current.DispatcherUnhandledException:
System.IO.FileNotFoundException: 
File name: 'FluentResults, Version=3.16.0.0, Culture=neutral, PublicKeyToken=null'
   at RanseiLink.GuiCore.ViewModels.ModListItemViewModel.PatchRom(ModInfo mod)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RanseiLink.GuiCore.ViewModels.ModListItemViewModel.PatchRom(ModInfo mod)
   at RanseiLink.GuiCore.ViewModels.ModListItemViewModel.<.ctor>b__8_1()
   at RanseiLink.GuiCore.ViewModels.RelayCommand.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Deijin27** [comment]
That's odd. The error message suggests that what you did was Patch a rom, not populate defaults. Along with the compliaint that FluentResults is missing. It suggests to me that your copy of ranseilink is corrupt, I'm not sure how though, maybe antivirus has modified the file, that's a total guess though.

I've tested it myself and successfully populated defaults.

I recommend trying redownloading RanseiLink and trying again.

**Comment by Deijin27** [comment]
Closing as cannot reproduce / stale
