### ISSUE TITLE
Cant open mod anymore

### ISSUE THREAD

**Issue by Schifer27** [Deijin27/RanseiLink#77]
### What happened?

I created a mod based off an existing one (reconquered). I was planning on replacing some pokemon, just for my own fun.  
After I replaced the images of around 40 pokemon, I closed it for the day. When I opened the program again to continue editing stats and such, I got this error.  
First time submitting something like this, so I hope this is explained enough.  
The other mods work fine. I'm a complete amateur btw, I have no idea what this error means. 

### Version

6.0

### Error Message

Application.Current.DispatcherUnhandledException:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RanseiLink.Core.Services.ModelServices.PokemonService.PostLoad(Stream stream)
   at RanseiLink.Core.Services.ModelServices.BaseDataModelService`1.Reload()
   at RanseiLink.Core.Services.ModelServices.BaseDataModelService`1..ctor(String dataFile, Int32 minId, Int32 maxId, Func`1 newModel, Int32 defaultId)
   at RanseiLink.Core.Services.ModelServices.PokemonService..ctor(String dataFile)
   at RanseiLink.Core.Services.ModelServices.PokemonService..ctor(ModInfo mod)
   at InvokeStub_PokemonService..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at DryIoc.Interpreter.TryInterpretSingletonAndUnwrapContainerException(IResolverContext r, Expression expr, ImMapEntry`1 itemRef, Object& result) in /_/src/DryIoc/Container.cs:line 3110
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 11136
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11055
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 12082
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11038
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 426
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 392
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 8602
   at RanseiLink.Core.Services.ServiceGetter.Get[T]()
   at RanseiLink.GuiCore.ViewModels.AbilitySelectorEditorModule.Initialise(IServiceGetter modServices)
   at RanseiLink.GuiCore.ViewModels.MainEditorViewModel.TryGetModule(String moduleId, EditorModule& module)
   at RanseiLink.GuiCore.ViewModels.MainEditorViewModel.SetCurrentModule(String moduleId, Boolean forceUpdate, Boolean blockStackPush)
   at RanseiLink.GuiCore.ViewModels.MainEditorViewModel.SetMod(ModInfo mod)
   at RanseiLink.GuiCore.ViewModels.MainWindowViewModel.OnModSelected(ModInfo mod)
   at RanseiLink.GuiCore.ViewModels.ModSelectionViewModel.<>c__DisplayClass47_0.<.ctor>b__1(ModInfo mi)
   at RanseiLink.GuiCore.ViewModels.RelayCommand`1.Execute(Object parameter)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Deijin27** [comment]
No worries, I've been able to reproduce the issue, investigating now.

**Comment by Deijin27** [comment]
Ok, I've fixed the issue. Will get a new version out tomorrow.

**Comment by Schifer27** [comment]
Sorry, I've only read this now.  
But that's awesome, wish I could've helped more with the file there.  
Looking forward to finishing my little project, you're awesome!

**Comment by Deijin27** [comment]
[New release out now](https://github.com/Deijin27/RanseiLink/releases/latest)

I wasn't possible to fully fix broken mods. As mentioned in the release notes, you will need to manually fix the evolutions of pokemon in your mod. This is the only problem though fortunately.

**Comment by Schifer27** [comment]
Thank you for all the incredible work, my fellow #27 user!
